FROM python:3.11-slim
WORKDIR /app

COPY ahorcado.py .
COPY palabras.txt .
COPY palabras_github.txt .
COPY requirements.txt .
COPY funciones.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python","ahorcado.py", "palabras.txt"]